### ISSUE TITLE
Settings: "Renpy Warn On" radio button toggles don't refresh open file(s)

### ISSUE THREAD

**Issue by Savage1969** [renpy/vscode-language-renpy#149]
Settings: "Renpy Warn On" radio button toggles (On or Off) don't take effect until manual file(s) close/load or via VSC restart 

Possible VSC technical limitation but if not it would be fantastic if the settings took immediate effect **OR** otherwise the code calls to bring up the VSC reload request info box like some theme settings currently do:
![image](https://user-images.githubusercontent.com/108280960/176050033-0c4d6e08-69a6-419e-82df-9bb41db10c54.png)

**Comment by JelleInfinity** [comment]
Thanks for pointing that out :)

I think this might be fixable with the same fix I applied to the othe config setting yesterday. (This setting change also isn't detected)

In fact, there are probably more settings that should update some code.

**Comment by LuqueDaniel** [comment]
I've been testing and it seems that the 4babb1b5 commit fixes this issue in almost all configuration options.

- ✔️ Exclude Rpyc Files From Workspace
- ❌ Show Automatic Images in Completion (only updates at restart). Depends on Whatch Folders For Changes which isn't supported on all platforms.
- ✔️ Warn On Indentation and Spacing Issues
- ✔️ Warn On Invalid Filename Issues
- ✔️ Warn On Invalid Variable names
- ✔️ Warn On Obsolete Method
- ✔️ Warn On Reserved Variable Names
- ✔️ Warn On Undefined Persitants
- ✔️ Warn On Undefined Store Variable

**Comment by duckdoom4** [comment]
@LuqueDaniel Does your PR also solve this issue?

**Comment by LuqueDaniel** [comment]
@duckdoom4 No PR #238 doesn't solve it, it only fixes #195. I'll review and check this issue 👍
