### ISSUE TITLE
Slow Performance (Intellisense primarily)

### ISSUE THREAD

**Issue by wampxs** [renpy/vscode-language-renpy#362]
Type: <b>Bug</b>

The Ren'Py VSCode addon has been faulty for a while now, since the last major update (the one that changed some text colors, I believe.)

The biggest harm I've felt is the now-unusably slow IntelliSense autocomplete results, which is lamentable. That is a feature I use constantly, and it's hampering my work-flow.

It also has an "Unresponsive" warning on the 'Running Extensions' window.

Extension version: 2.2.2/2.3.6 (both seem to have the same issue)
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19044

CPU is a Ryzen 7 3800x.

**Comment by duckdoom4** [comment]
That's unfortunate. To figure out the exact cause we'll need some help though. If it's taking a long time to complete an action in your project, it's likely that some part of your codebase triggers a bug in the extension.
I've not ran into performance issues in my test projects.

**Comment by wampxs** [comment]
Is this it?

[CPU-20230709T141159.cpuprofile.txt](https://github.com/LuqueDaniel/vscode-language-renpy/files/11995730/CPU-20230709T141159.cpuprofile.txt)

**Comment by duckdoom4** [comment]
No sorry, I should have specified. If you follow the gif, they use the load function of the profiler. But that's what we need to do.

If you could do the same steps as shown in the gif, but choose the option to make a new profile.

When you start a session, vscode will record what the code is doing, so make sure you do the actions that will trigger the slowdown.

Then you can stop the session and upload the results. We should then be able to see the parts of the code that take a long time in your project

**Comment by wampxs** [comment]
I actually did that. 
Started recording, then tried auto-completing one variable (which gave me the expected slowdown), then stopped once it found the variable name.

The file I sent was the cpuprofile log generated from that. 
Just remove the '.txt', Github doesn't allow uploading the .cpuprofile format for some reason. That should let you load it on the profiler 
(I tested it myself, though I have no clue what the results mean 😪)

**Comment by duckdoom4** [comment]
Hmm, well the profile you've uploaded doesn't go through any of our source code. It only mentioned`workbench.desktop.main.js`.

Are you sure it is our plugin and not something else?

And/or are you sure you triggered the slowdown while you made the cpu profile?

**Comment by wampxs** [comment]
Huh... The file I sent was a different kind of recording then. That was straight from the devtools.
Just tried recording from the "Running Extensions" window instead, see if this one shows anything relevant.

[CPU-20230710T073226.348Z.cpuprofile.txt](https://github.com/LuqueDaniel/vscode-language-renpy/files/11999076/CPU-20230710T073226.348Z.cpuprofile.txt)

**Comment by duckdoom4** [comment]
That one does show different information. I'll have a look after work

**Comment by wampxs** [comment]
Just updating the situation here...
Rolling back to version 2.2.1 immediately solved this issue. 
It's definitely from 2.2.2 and onwards.

**Comment by wampxs** [comment]
Seems like rolling back to 2.0.16 fixed the slowness issues. Very likely to be a 2.2.x thing.
Not only do Intellisense results show up instantly, but saving times are faster too. These were very sluggish in the newer update.

**Comment by duckdoom4** [comment]
Hm, yes alright. That's enough proof then. I'll try to see if I can find the issue/what I can do about it.

**Comment by Kant8** [comment]
For me it's constantly hangs on "Initializing Ren'Py static data" right after vscode startup. Can sit like that for half an hour easily. And vscode complains about "very slow last operation" from extension. 
Even search for files doesn't work properly until that intialization ends.

No problems if extension is disabled.

**Comment by duckdoom4** [comment]
> For me it's constantly hangs on "Initializing Ren'Py static data" right after vscode startup. Can sit like that for half an hour easily. And vscode complains about "very slow last operation" from extension. 
> Even search for files doesn't work properly until that intialization ends.
> 
> No problems if extension is disabled.

Ah yes, I was hoping that issue would be fixed with the latest update, but clearly not.

Would you be able to figure out what file exactly is causing the issue? It should be one  (or more) specific files in your project.

If you'd be able to share it with me (privately if necessary) then I can debug the issue and fix it.

**Comment by quocmanh94** [comment]
[exthost-f2d60a.cpuprofile.txt](https://github.com/LuqueDaniel/vscode-language-renpy/files/12228753/exthost-f2d60a.cpuprofile.txt)
I met the same problem when I was starting VSC.

**Comment by lust-reborn** [comment]
Same issue on v2.2.2 and pre-release v2.3.6

> vscode complains about "very slow last operation" from extension. Even search for files doesn't work properly until that intialization ends.

extension causes all other extensions to fail. they just hang after "intilization"

**Comment by DeltaGe** [comment]
Yep, I can confirm, the extension does not work, stuck on loading renpy static data, and until it is uninstalled it disables intellisense entirely

**Comment by brainos233** [comment]
Still exists in 2.4.0

**Comment by duckdoom4** [comment]
I've made it 10x faster, so it shouldn't be a problem with slowness anymore. There could still be the issue of it getting stuck though, but we already have a different issue for that
