### ISSUE TITLE
Wrong float highlight when having digits both before and after the dot

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/vscode-language-renpy#363]
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/44340603/6ff9c307-6e28-4743-866c-25e462c71889)
The 0.0 is part of the default gui.rpy. Notice how the part after the dot gets red iff there's no part before the dot.
Also, when there's no part before the dot, the dot is orange instead of white for some reason, while they should probably be all white or all orange.

**Comment by duckdoom4** [comment]
Ah yes, those are slightly different. Thanks for the report :)

**Comment by duckdoom4** [comment]
I think this one's fixed
