### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by StephenJBrasel** [renpy/vscode-language-renpy#39]
- Issue Type: `Performance`
- Extension Name: `languague-renpy`
- Extension Version: `2.0.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.2`

:warning: See **attached**:
:warning:[`c:\Users\Stephen\AppData\Local\Temp\LuqueDaniel.languague-renpy-unresponsive.cpuprofile.txt`](https://github.com/LuqueDaniel/vscode-language-renpy/files/7406108/LuqueDaniel.languague-renpy-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JelleInfinity** [comment]
Might be fixed as of v2.1.0-pre-release. Will need some testing, though I will say most cpu intensive code is still not updated to use the new tokenizer
