### ISSUE TITLE
Missing colors for group & attribute in a layered image

### ISSUE THREAD

**Issue by kiirdonel** [renpy/vscode-language-renpy#409]
### Extension version

2.2.2

### Issue description

When making a layered image, "attribute" receives no color and "group" only receives a color when given a variant.
![Screenshot 2024-06-19 135027](https://github.com/renpy/vscode-language-renpy/assets/18373944/72a3fa3d-619b-4252-a063-2724af8c708d)

### Scope inspector screenshots

The functioning "group":
![Screenshot 2024-06-19 135112](https://github.com/renpy/vscode-language-renpy/assets/18373944/6c4f9edb-1fe7-4648-a1a3-6a25c20b48cd)
The non-functioning "group":
![Screenshot 2024-06-19 135129](https://github.com/renpy/vscode-language-renpy/assets/18373944/ef032715-8006-4ea3-8ddd-4111ecca5241)
The non-functioning "attribute":
![Screenshot 2024-06-19 135137](https://github.com/renpy/vscode-language-renpy/assets/18373944/1047d376-107c-496a-ae4b-ad16bc31f328)

### Code

```
layeredimage dave:

    group arms variant "casual":
        attribute neutral default

    group clothes:
        attribute casual default
```

**Comment by duckdoom4** [comment]
Thanks for the report! It seems group has not been handled in the syntax highlighter files. We'll have to add it.

(Can't promise when it will be done though)

**Comment by kiirdonel** [comment]
No problem, thank you for taking a look! :)
