### ISSUE TITLE
Generating renpy.json from sphinx. 

### ISSUE THREAD

**Issue by renpytom** [renpy/vscode-language-renpy#412]
@LuqueDaniel, @duckdoom4 

So, looking at renpy.json, I realize a lot of the generation script seems to duplicate what's already being done to generate the Sphinx documentation. As a prototype, I went ahead and wrote a script that parses the reStructuredText to find all of the variables, functions, and classes, and output them in the format. 

The script is at https://github.com/renpy/renpy/blob/to-renpy-json/sphinx/to_renpy_json.py , 

I think it will require a bit more work, and either coding the names for the namespaces into the script or documenting them in the Sphinx, but I think I like this approach a bit better than having two separate documentation scripts. 

There's also the most basic support for the accessKind field - I'll look into fixing that. 

Just tossing this out there. I'm still a bit green when it comes to this.

**Comment by duckdoom4** [comment]
Sounds good to me. That script and surrounding features hasn't been touched in years, so feel free to do with it as you please

**Comment by renpytom** [comment]
Okay, this is now being done as part of the Ren'Py  documentation build process (though for now, I'll have to copy the renpy.json file over by hand).
